messages:
  terra_purge_command: "&2&l[SERVER] &a/terrapurge <name> <amount>"
  terra_purge_item_gave: "&2&l[SERVER] &aYou gave {amount} excavation item to {player}"
  terra_purge_confirmed: "&2&l[SERVER] &aPlot excavation confirmed"
  terra_purge_cancelled: "&2&l[SERVER] &cPlot excavation cancelled"

require_confirmation: true
confirmation_inventory:
  title: "Escavar Terreno - Confirmar"
  size: 27
  items:
    confirm:
      slot: 11
      id: LIME_TERRACOTTA
      name: "&2&lCONFIRMAR"
      glow: false
      description:
        - ""
      sound: BLOCK_NOTE_BLOCK_BELL
    cancel:
      slot: 15
      id: RED_TERRACOTTA
      name: "&c&lCANCELAR"
      glow: false
      description:
        - ""
      sound: BLOCK_ANVIL_USE

item:
  id: STONE
  name: "&eLimpador de Terrenos"
  glow: true
  description:
    - ""
    - "&aClique com o botão direito"
    - "&ano seu terreno para limpar"
    - "&atodos os blocos"
    - ""
